### ISSUE TITLE
Component getter based on args is not re-evaluated

### ISSUE THREAD

**Issue by ffaubry** [glimmerjs/glimmer.js#207] opened 2019-08-13 20:31 UTC
I have created a repo to reproduce this issue.
https://github.com/ffaubry/octane-args-bug

Steps:
- run the app
- you should get on the page 'Ember - Ember'
- click the button 'Update Foo'
- you should see on the page 'Ember# - Ember#
- you will get 'Ember - Ember#'

The getter in the component ArgsBug is never re-evaluated despite the args being changed

The master branch is based on the latest octane blueprint. If you run the code you will see an error message in the console:
![image](https://user-images.githubusercontent.com/3506166/62974942-200ac480-bdce-11e9-9eeb-1b79b47642a3.png)

The branch 'ember-3.12' is using ember-cli 3.11 and ember-source 3.12 and the issue is different.

I think the tracker is broken somewhere...

**Comment by ffaubry** [comment] 2019-08-13 23:42
I'm tracking this down. Somehow, I think this is related to ember-template-lint 1.5.0 that is pulling glimmer/compiler and others with a different version...
Not sure yet why.

**Comment by amk221** [comment] 2020-02-27 00:10
How come nobody else has noticed this? Maybe raise in ember.js repo?

**Comment by pzuraq** [comment] 2020-02-27 00:19
The issues with args proxy have been solved for a while now, there were a lot of issues opened up on the Ember.js repo at the time. We closed them there, and forgot to close this one, but since it's very out of date I'm going to close for now. 

If you can provide a reproduction that fails on Ember 3.16, let us know and we can reopen.

**Closed** 2020-02-27 00:19 UTC

**Comment by ffaubry** [comment] 2020-02-27 00:21
I agree we can close. Things got much better.
We are on 3.16 and happy.
