### ISSUE TITLE
BUG: Cannot getting started due to error while installation on Windows 10

### ISSUE THREAD

**Issue by redstrike** [glimmerjs/glimmer.js#88] opened 2017-11-28 07:39 UTC
I tried on both Active LTS and Current Stable version of Node.js, still meet this issue.

```
PS C:\Users\Red\Desktop> ember new my-app -b @glimmer/blueprint
WARNING: Node v9.2.0 is not tested against Ember CLI on your platform. We recommend that you use the most-recent "Active LTS" version of Node.js. See https://git.io/v7S5n for details.
installing blueprint
  create .editorconfig
  create .ember-cli
  create .watchmanconfig
  create README.md
  create config\environment.js
  create config\module-map.d.ts
  create config\resolver-configuration.d.ts
  create config\targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public\robots.txt
  create src\index.ts
  create src\main.ts
  create src\ui\components\MyApp\component-test.ts
  create src\ui\components\MyApp\component.ts
  create src\ui\components\MyApp\template.hbs
  create src\ui\index.html
  create src\ui\styles\app.scss
  create src\utils\test-helpers\test-helper.ts
  create testem.json
  create tsconfig.json
  create tslint.json
  create yarn.lock
Error creating new application. Removing generated directory `./my-app`
Command failed: yarn install --ignore-optional --non-interactive
warning qunitjs@2.4.1: 2.4.1 is the last version where QUnit will be published as 'qunitjs'. To receive future updates, you will need to change the package name to 'qunit'.
warning "@glimmer/application-pipeline > ember-build-utilities@0.4.0" has unmet peer dependency "@glimmer/compiler@> 0.26.0".
warning " > @glimmer/inline-precompile@1.0.1" has unmet peer dependency "@glimmer/compiler@> 0.23.0 || > 0.24.0-alpha.1 || > 0.25.0-alpha.1".
warning "@glimmer/inline-precompile > babel-plugin-glimmer-inline-precompile@1.2.0" has unmet peer dependency "@glimmer/compiler@> 0.23.0 || > 0.24.0-alpha.1 || > 0.25.0-alpha.1".
error C:\Users\Red\Desktop\my-app\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\Red\Desktop\my-app\node_modules\node-sass
Output:
Building: C:\nodejs\node.exe C:\Users\Red\Desktop\my-app\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Red\\Desktop\\my-app\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.2.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Red\Desktop\my-app\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Red\Desktop\my-app\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Red\Desktop\my-app\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Red\Desktop\my-app\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Red\Desktop\my-app\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Red\Desktop\my-app\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Red\Desktop\my-app\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Red\Desktop\my-app\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Red\Desktop\my-app\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Red\Desktop\my-app\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Red\Desktop\my-app\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Red\Desktop\my-app\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\Red\\Desktop\\my-app\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Red\\Desktop\\my-app\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Red\\Desktop\\my-app\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Red\\Desktop\\my-app\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Red\\Desktop\\my-app\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Red\\Desktop\\my-app\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python36\python.EXE
gyp verb check python version `C:\Python36\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.3\r\n"
gyp verb could not find "C:\Python36\python.EXE". checking python launcher
gyp verb could not find "C:\Python36\python.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Red\Desktop\my-app\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Red\Desktop\my-app\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\Red\Desktop\my-app\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\Red\\Desktop\\my-app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Red\Desktop\my-app\node_modules\node-sass
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1

yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

Error: Command failed: yarn install --ignore-optional --non-interactive
warning qunitjs@2.4.1: 2.4.1 is the last version where QUnit will be published as 'qunitjs'. To receive future updates, you will need to change the package name to 'qunit'.
warning "@glimmer/application-pipeline > ember-build-utilities@0.4.0" has unmet peer dependency "@glimmer/compiler@> 0.26.0".
warning " > @glimmer/inline-precompile@1.0.1" has unmet peer dependency "@glimmer/compiler@> 0.23.0 || > 0.24.0-alpha.1 || > 0.25.0-alpha.1".
warning "@glimmer/inline-precompile > babel-plugin-glimmer-inline-precompile@1.2.0" has unmet peer dependency "@glimmer/compiler@> 0.23.0 || > 0.24.0-alpha.1 || > 0.25.0-alpha.1".
error C:\Users\Red\Desktop\my-app\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Users\Red\Desktop\my-app\node_modules\node-sass
Output:
Building: C:\nodejs\node.exe C:\Users\Red\Desktop\my-app\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ 'C:\\nodejs\\node.exe',
gyp verb cli   'C:\\Users\\Red\\Desktop\\my-app\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@9.2.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Red\Desktop\my-app\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Red\Desktop\my-app\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Red\Desktop\my-app\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Red\Desktop\my-app\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Red\Desktop\my-app\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Red\Desktop\my-app\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed  python2 { Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Users\Red\Desktop\my-app\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Users\Red\Desktop\my-app\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Users\Red\Desktop\my-app\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Users\Red\Desktop\my-app\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Users\Red\Desktop\my-app\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Users\Red\Desktop\my-app\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqWrap.oncomplete (fs.js:166:21)
gyp verb `which` failed   stack: 'Error: not found: python2\n    at getNotFoundError (C:\\Users\\Red\\Desktop\\my-app\\node_modules\\which\\which.js:13:12)\n    at F (C:\\Users\\Red\\Desktop\\my-app\\node_modules\\which\\which.js:68:19)\n    at E (C:\\Users\\Red\\Desktop\\my-app\\node_modules\\which\\which.js:80:29)\n    at C:\\Users\\Red\\Desktop\\my-app\\node_modules\\which\\which.js:89:16\n    at C:\\Users\\Red\\Desktop\\my-app\\node_modules\\isexe\\index.js:42:5\n    at C:\\Users\\Red\\Desktop\\my-app\\node_modules\\isexe\\windows.js:36:5\n    at FSReqWrap.oncomplete (fs.js:166:21)',
gyp verb `which` failed   code: 'ENOENT' }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python36\python.EXE
gyp verb check python version `C:\Python36\python.EXE -c "import platform; print(platform.python_version());"` returned: "3.6.3\r\n"
gyp verb could not find "C:\Python36\python.EXE". checking python launcher
gyp verb could not find "C:\Python36\python.EXE". guessing location
gyp verb ensuring that file exists: C:\Python27\python.exe
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Python36\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\Red\Desktop\my-app\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\Red\Desktop\my-app\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Users\Red\Desktop\my-app\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\nodejs\\node.exe" "C:\\Users\\Red\\Desktop\\my-app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\Red\Desktop\my-app\node_modules\node-sass
gyp ERR! node -v v9.2.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1

yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    at Promise.all.then.arr (C:\Users\Red\AppData\Local\Yarn\config\global\node_modules\execa\index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by tomdale** [comment] 2017-11-29 13:03
It looks like this is failing during compilation of node-sass? We had deprecated it because of issues like this. Maybe now is a good time to rip the bandaid off. @rwjblue @locks?

**Comment by tomdale** [comment] 2017-11-29 13:04
Also, I really appreciate you filing this report. Windows compatibility is very important to us. We will get this fixed. I'm sorry for the trouble you ran into.

**Comment by t-sauer** [comment] 2017-11-29 13:15
The deprecated SASS support was removed in @glimmer/application-pipeline a while ago and is published as 0.10.0. The default blueprint still references @glimmer/application-pipeline@0.8.0 though.
I am not sure though if that completely solves the problem since ember-cli-sass is included in the blueprint (so by default node-sass will be installed anyway). 
Maybe ember-cli-sass uses a newer node-sass version which comes with pre-built libsass, otherwise you need to get node-sass building on windows machines. To do that the node-gyp prerequisites are required which can be found here: https://github.com/nodejs/node-gyp#on-windows

**Comment by redstrike** [comment] 2017-11-29 18:20
I have a globally installed **node-sass** while starting the project.
Not sure if it causes any compatibility problem with Ember CLI?

**Comment by teyc** [comment] 2018-01-29 12:02
I'm getting the same problem on OS X.
```
Error creating new application. Removing generated directory `./ember-crud`
Command failed: yarn install --ignore-optional --non-interactive
warning qunitjs@2.4.1: 2.4.1 is the last version where QUnit will be published as 'qunitjs'. To receive future updates, you will need to change the package name to 'qunit'.
warning "@glimmer/application-pipeline > ember-build-utilities@0.4.0" has unmet peer dependency "@glimmer/compiler@> 0.26.0".
warning " > @glimmer/inline-precompile@1.0.1" has unmet peer dependency "@glimmer/compiler@> 0.23.0 || > 0.24.0-alpha.1 || > 0.25.0-alpha.1".
warning "@glimmer/inline-precompile > babel-plugin-glimmer-inline-precompile@1.2.0" has unmet peer dependency "@glimmer/compiler@> 0.23.0 || > 0.24.0-alpha.1 || > 0.25.0-alpha.1".
error /Users/Chui/Toyapps/ember-crud/node_modules/broccoli-sass-source-maps/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: /Users/Chui/Toyapps/ember-crud/node_modules/broccoli-sass-source-maps/node_modules/node-sass
Output:
module.js:529
    throw err;
    ^

Error: Cannot find module 'boom'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/Chui/Toyapps/ember-crud/node_modules/hawk/lib/index.js:3:33)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
```

**Comment by tomdale** [comment] 2018-01-29 21:06
@teyc I'm seeing this issue now too. It looks like the root cause is https://github.com/yarnpkg/yarn/issues/4576. Ember CLI invokes `yarn install` with `--ignore-optional`, which leaves the node_modules tree in a broken state.

**Comment by tomdale** [comment] 2018-01-29 21:08
This should be fixed upstream in Ember CLI: https://github.com/ember-cli/ember-cli/pull/7573

**Comment by teyc** [comment] 2018-01-29 23:01
Thanks Tom.  As a workaround 

`ember new my-app -b @glimmer/blueprint --skip-npm` 

works for me

**Comment by locks** [comment] 2020-04-18 10:24
Closing as resolved upstream.

**Closed by locks** 2020-04-18 10:24 UTC
