### ISSUE TITLE
Blueprint doesn't generate src files

### ISSUE THREAD

**Issue by betocantu93** [glimmerjs/glimmer.js#311] opened 2020-10-03 18:56 UTC
Hello, trying out glimmer blueprint with `ember new hello-world-2 -b @glimmer/blueprint` doesn't generate the src directory and so it fails to `ember s`

**Comment by drewmcdonald1337** [comment] 2020-11-12 04:12
I ran into this, I think it's a duplicate of #229 .

**Comment by locks** [comment] 2022-02-15 17:52
I believe this applied to pre-v2 versions, so no longer relevant!

**Closed by locks** 2022-02-15 17:52 UTC
