### ISSUE TITLE
actions don't work in svg

### ISSUE THREAD

**Issue by fredguth** [glimmerjs/glimmer.js#103] opened 2018-01-25 12:13 UTC
According to the documentation (https://www.w3.org/TR/SVG/interact.html), svg has `onclick`. Here is my try.glimmer example: http://tinyurl.com/y7bdn3n7

Relates to https://github.com/emberjs/ember.js/issues/13420

**Comment by tomdale** [comment] 2018-03-16 00:26
The root cause of this is that we special case the SVG namespace and only set attributes when we're in that context. The normal `onclick` behavior relies on us setting properties.

The planned fix for this is to always set attributes and introduce a helper for setting properties or adding event listeners.

**Comment by locks** [comment] 2020-04-18 10:38
We now have the `on` modifier for adding event listeners which should work in the SVG namespace.

**Closed by locks** 2020-04-18 10:38 UTC
