### ISSUE TITLE
Unhelpful error when typo in html args

### ISSUE THREAD

**Issue by BryanCrotaz** [glimmerjs/glimmer.js#282] opened 2020-04-17 17:23 UTC
Ember 3.17 with glimmer:

Write `<button @class="myclass"/>` instead of the correct `<button class="myclass"/>`
You get a VERY cryptic runtime error
`TypeError: func is not a function`

This sounds like it's a misuse of `{{on}}` and `{{fn}}` which directs the developer to the wrong conclusion.

All glimmer parsing/runtime errors like this should include a file:line:column reference to the faulty template.

**Comment by pzuraq** [comment] 2020-04-17 18:56
Agreed, we've had a long standing issue about needing to make template parse errors better 😕 I think we should invest in this sooner rather than later

**Comment by BryanCrotaz** [comment] 2020-04-17 19:10
It's especially important for new devs' first impressions of Octane. They're likely to make mistakes and the platform should help them out.

**Comment by BryanCrotaz** [comment] 2020-04-17 19:14
Related to https://github.com/glimmerjs/glimmer.js/issues/43 ?

**Comment by pzuraq** [comment] 2020-04-17 19:28
I think that error is likely more related to Glimmer.js v1, which used the bundle compiler and did a lot of work ahead of time. With modern Ember that would be a much nicer error message

**Comment by locks** [comment] 2020-04-18 15:26
Thanks for reporting. Closing as duplicate of https://github.com/glimmerjs/glimmer-vm/issues/747 !

**Closed by locks** 2020-04-18 15:26 UTC
