### ISSUE TITLE
Blueprint not generating src directory

### ISSUE THREAD

**Issue by kiannaquach** [glimmerjs/glimmer.js#281] opened 2020-01-23 18:02 UTC
I followed the "Installing" and "Getting Started" guide on https://glimmerjs.com/guides/installing, and was not able to run my-app since there wasn't a src directory generated after running `ember new my-app -b @glimmer/blueprint`. I checked my ember-cli version and I believe I'm in the correct version. Any ideas on why a src directory wasn't generated, and how I can resolve this issue?

Copied from my terminal:
```
kiannaq. desktop$ ember --version
ember-cli: 3.15.1
node: 12.8.0
os: darwin x64

kiannaq. desktop$ ember new my-app -b @glimmer/blueprint
installing blueprint
  create .editorconfig
  create .ember-cli
  create .template-lintrc.js
  create .watchmanconfig
  create README.md
  create config/environment.js
  create config/module-map.d.ts
  create config/resolver-configuration.d.ts
  create config/targets.js
  create ember-cli-build.js
  create .gitignore
  create package.json
  create public/robots.txt
  create testem.json
  create tests/index.html
  create tsconfig.json
  create tslint.json

🚧  Installing packages... This might take a couple of minutes.
npm: Installed dependencies

🎥  Initializing git repository.
Git: successfully initialized.

🎉  Successfully created project my-app.
👉   Get started by typing:

  $ cd my-app
  $ npm start

Happy coding!
kiannaq. desktop$ cd my-app

kiannaq. my-app$ npm start
> my-app@0.0.0 start /Users/kiannaq./Desktop/my-app
> ember server

Could not find a src/ directory. Create a directory called 'src' in the root of your project.
```

**Comment by locks** [comment] 2020-04-18 10:13
Duplicate of https://github.com/glimmerjs/glimmer.js/issues/229.

**Closed by locks** 2020-04-18 10:13 UTC
Labels: v1.x
