### ISSUE TITLE
IE & Edge Support

### ISSUE THREAD

**Issue by zidjian257** [glimmerjs/glimmer.js#8] opened 2017-09-07 16:13 UTC
Hi,

a new untouched glimmerjs app with `ember new my-app -b @glimmer/blueprint` runs in firefox and chrome but not in ie or edge.

Edge gives me following error: 
```
SCRIPT1028: Expected identifier, string or number: 
app.js (3386,11)
``` 
IE11:
```
SCRIPT1002: Syntaxfehler
app.js (7,1)
```

Is this an known issue?
Does GlimemrJS support MS Browsers at all?

**Comment by t-sauer** [comment] 2017-09-07 16:25
For IE you have to add IE 11 to your targets in `config/targets.js` otherwise your code is not transpiled to a javascript version IE11 supports.

**Comment by rwjblue** [comment] 2017-09-08 00:26
It should support Edge out of the box though.... 🤔

**Comment by zidjian257** [comment] 2017-09-08 09:13
Thanks for your fast reply.

With adding `IE11` the app now runs with "Microsoft Edge", but still not with IE11.

IE11 provides following error, which referes to a `let` Symbol:
```
SCRIPT5009: "Symbol" ist undefiniert
app.js (9804,1)
```
Any other settings we need to change?

Also it's a little bit strange that with setting `IE11` the Edge problem got fixed.
Or that the default setting 'last 2 Edge versions' does not transpile to a edge compatible version...

**Comment by ro0t** [comment] 2017-09-22 11:35
I am also having issues with IE 11 support, added 'ie 11' into targets.js file but it's still not working.

@zidjian257 FYI: I got rid of that Symbol is undefined error by including babel-polyfill.

**Comment by zidjian257** [comment] 2017-09-25 11:04
@ro0t how did you include babel-polyfill?

**Comment by zidjian257** [comment] 2017-09-25 13:01
OK I digged a little bit deeper and checked out babel-polyfill.
My current status is, that I got it running under EDGE and IE 11 with following settings:

targets.js
```
let browsers = [
  '> 5%',
  'last 2 Edge versions',
  'last 2 Chrome versions',
  'last 2 Firefox versions',
  'last 2 Safari versions',
  'IE 9',
  'IE 10',
  'IE 11'
];
```

for IE 11 I had to add the babel-polyfill. The way I did it is just adding it to the index.html, but I'm sure there is a better way to include it.
`npm install babel-polyfill` and adding `require('babel-polyfill')` to the ember-cli-build.js file did not help.
Also using ember-cli-babel plugin and add `'ember-cli-babel': { includePolyfill: true }` to the ember-cli-build.js resulted in an error as glimmerjs does not support `app.import`.

**Would be great if someone could tell me how to add libraries the right way to a glimmerjs app.**

After this it seems to run with EDGE and IE 11.
But unfortnatelly it still does not load in IE 10 or IE 9.
In these browsers it throws an exception in `Container.prototype.buildFactory.create` saying Object has no **create** method when it is called with factoryDefinition == function GlimmerApp() 

While debugging I set `factoryDefinition.create = Object.create` for the GlimmerApp. Then the App started rendering but at the end it throws an exception saying _method didInsertElement is not defined_ 

Does anyone have an idea how to properly solve IE compability?

**Comment by t-sauer** [comment] 2017-09-26 10:35
I figured out why it is not working in Edge but I am not sure yet if it is an Edge bug.  
In the current used Glimmer version, there is a class method called `static` which won't be transpiled if you target Edge (see https://github.com/glimmerjs/glimmer-vm/blob/v0.26.2/packages/%40glimmer/runtime/lib/compiler.ts#L225). That's the code where Edge starts complaining. It expects an identifier afterwards so I assume that Edge thinks that it is a static property and it expects a name for it. Small reproduction can be found here: https://jsfiddle.net/9jn5xe9g/  
I am not sure if methods called `static` are allowed per spec. If yes, then this is an Edge bug.

**Comment by zidjian257** [comment] 2017-09-26 10:45
here it says you are not allowed to use static: https://www.w3schools.com/js/js_reserved.asp

**Comment by rwjblue** [comment] 2017-09-26 21:17
@t-sauer - Awesome sleuthing!  We should:

* Update this case to avoid using `static` as a method name (and update its callers)
* File a bug with the Edge team so they can look into it, I believe this method name should be allowed

**Comment by t-sauer** [comment] 2017-09-26 23:16
I've create an issue for it: https://github.com/Microsoft/ChakraCore/issues/3816

**Comment by ro0t** [comment] 2017-10-15 17:18
**I updated to latest GlimmerJS and included this, everything works in IE11 now for me!!!!**
<script src="https://cdn.polyfill.io/v2/polyfill.js?features=default,fetch,Promise"></script>

**Comment by rwjblue** [comment] 2017-10-15 20:44
FWIW, Glimmer.js does not intend to support IE11, if it is working for you now that seems great, but it is definitely not part of our supported browser matrix...

**Comment by t-sauer** [comment] 2017-10-15 22:13
@rwjblue Is it documented which browsers are supported? I can't find it but I assume it's latest Edge, Firefox, Chrome and Safari?

**Comment by rwjblue** [comment] 2017-10-16 02:10
I believe https://github.com/glimmerjs/glimmer-blueprint/blob/master/files/config/targets.js was supposed to be the canonical source, but we should get a better listing up on the website and whatnot too.

**Comment by ASH-Anthony** [comment] 2017-12-08 21:41
@rwjblue I know IE's usage is low globally, but a lot of mid-size+ companies force their users to use IE. For companies who have a lot of corporate clients (as is our case), we have a large share of IE users, even though we only support IE11. We're committed to Ember and I am excited to use glimmer for smaller components, but this alone will probably stop us from using it (glimmer) in the near future.

**Comment by ro0t** [comment] 2017-12-22 15:03
@zidjian257 did you get it to work with the polyfill?

**Comment by dkalinin** [comment] 2019-12-19 11:36
We wanted to have a small application written on glimmer to complement our huge Ember application. In the end, we use Vue.js because it supports IE11.

**Comment by acorncom** [comment] 2019-12-19 19:00
@dkalinin there were changes that went through as part of the latest release (to 1.0) for Glimmer components that should have addressed the IE11 compatibility snags: https://github.com/glimmerjs/glimmer.js/pull/227 Might be worth a look?

**Comment by locks** [comment] 2019-12-19 20:51
Closing this issue as it seems resolved. Please open new issues if you encounter specific problems!

**Closed by locks** 2019-12-19 20:51 UTC
